config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # orders
  post '/order',    to: 'orders#create'

  # sessions 
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # signup
  get '/signup',		to: 'users#new'
  post '/signup',   to: 'users#create'

  # portfolio
  get '/portfolio', to: 'users#portfolio'
		
  # static pages
  get '/help',			to: 'static_pages#help'
  get '/about',			to: 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # routes for /users/<id>
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user

  before_save { self.currency = currency.upcase }
  validates(:currency, presence: true,
                       inclusion: { in: %w(USD BTC) } )
end

app/models/user.rb
class User < ApplicationRecord
  has_many :portfolio
  has_many :order

  before_save { self.email = email.downcase }
  validates(:name, presence: true,  length: { maximum: 50 })
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, length: { maximum: 212 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } )

  has_secure_password
  validates(:password, presence: true, length: { minimum: 6 })

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include ApplicationHelper
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    from_symbol = params[:order][:from_symbol]
    to_symbol   = params[:order][:to_symbol]
    amount      = params[:order][:amount].to_f

    current_USD = current_user.portfolio.find_by_currency("USD").amount
    current_BTC = current_user.portfolio.find_by_currency("BTC").amount

    current_BTC_price = getBTCPrice()
    
    # Values can't be negative
    if amount < 0 
      flash[:danger] = "Invalid amount #{amount}."
      redirect_to root_path
      return
    end
    
    # Check if from and to are the same
    if from_symbol.eql? to_symbol
      flash[:danger] = "Invalid order from #{from_symbol} to #{to_symbol}."
      redirect_to root_path
      return
    end
    
    # Check if there is enough money
    if from_symbol.eql? "USD" 
      if amount > current_USD  
        flash[:danger] = "Your USD is not enough."
        redirect_to root_path
        return
      end
    else
      if amount > current_BTC 
        flash[:danger] = "Your BTC is not enough."
        redirect_to root_path
        return
      end
    end

    @order = Order.new(user_id: current_user.id,
                       from_symbol: from_symbol,
                       to_symbol: to_symbol,
                       amount: amount)
    if @order.save
      flash[:success] = "You complete an order"

      if from_symbol.eql? "USD" 
        new_USD = current_USD - amount
        new_BTC = current_BTC + amount / current_BTC_price
      else
        new_BTC = current_BTC - amount
        new_USD = current_USD + amount * current_BTC_price
      end
      portfolio_USD = Portfolio.find_by(user_id: current_user.id, currency: "USD")
      portfolio_USD.amount = new_USD
      portfolio_USD.save!
      portfolio_BTC = Portfolio.find_by(user_id: current_user.id, currency: "BTC")
      portfolio_BTC.amount = new_BTC
      portfolio_BTC.save!

      redirect_to root_path
    else
      flash[:danger] = "There is some error"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
     log_out
     redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
require 'net/http'
require 'json'

class StaticPagesController < ApplicationController
  def home
    url = "https://api.coindesk.com/v1/bpi/currentprice.json"
    uri = URI(url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(uri.path, {'Content-Type' => 'application/json'})
    response = http.request(request)
    
    @responseValue = JSON.parse(response.body)
  end

  def help
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to CryptoTrader!"

      # Create allocation for USD and BTC for user
      portfolio_btc = Portfolio.new(user_id: @user.id, currency: "BTC", amount: 0.0)
      portfolio_btc.save
      portfolio_usd = Portfolio.new(user_id: @user.id, currency: "USD", amount: 1000000.0)
      portfolio_usd.save

      redirect_to @user
    else
      render 'new'
    end
  end

  def portfolio 
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'CryptoTrader'
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def getBTCPrice()
    url = "https://api.coindesk.com/v1/bpi/currentprice.json"
    uri = URI(url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(uri.path, {'Content-Type' => 'application/json'})
    response = http.request(request)
    
    @responseValue = JSON.parse(response.body)
    
    @responseValue["bpi"]["USD"]["rate"].gsub(/[^\d\.]/, '').to_f
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any.
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "CryptoTrader", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Portfolio", portfolio_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>

      <footer class="footer">
        <small>
          The CryptoTrader Application by Teerapat Jenrungrot
        </small>
        <nav>
          <ul>
            <li><%= link_to "About", about_path %></li>
          </ul>
        </nav>
      </footer>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This program is developed by Teerapat Jenrungrot.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  This page describes how to use our program.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>CryptoTrader</h1>
<p>
  This is the CryptoTrader App developed in Ruby on Rails.
</p>
<p>
  Time:
  <%= @responseValue["time"]["updatedISO"] %>
</p>
<p>
  Price in USD:
  <%= @responseValue["bpi"]["USD"]["rate"] %>
</p>
<% if !logged_in? %>
<div class="center jumbotron">
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

<% if logged_in? %>
<div class="panel-group">
  <div class="panel panel-success">
    <div class="panel-heading">Trader</div>
    <div class="panel-body">
      Currently, you have
      <ul>
        <li><%= current_user.portfolio.find_by_currency("USD").amount if current_user && current_user.portfolio.find_by_currency("USD") %> USD</li>
        <li><%= current_user.portfolio.find_by_currency("BTC").amount if current_user && current_user.portfolio.find_by_currency("BTC") %> BTC</li>
      </ul>

      <%= form_for(Order.create, url: order_path) do |f| %>
      <%= f.label :from_symbol %>
      <%= f.select :from_symbol, options_for_select([["US Dollar (USD)", "USD"], ["Bitcoin (BTC)", "BTC"]], "USD"), {}, {class: 'form-control'} %>

      <%= f.label :to_symbol %>
      <%= f.select :to_symbol, options_for_select([["US Dollar (USD)", "USD"], ["Bitcoin (BTC)", "BTC"]], "BTC"), {}, {class: 'form-control'} %>
      
      <%= f.label :amount %>
      <%= f.text_field :amount, class: 'form-control' %>

      <%= f.submit "Submit an order", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'  %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control'  %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control'  %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/portfolio.html.erb
<% provide(:title, "Portfolio and Order History") %>

<h1>Portfolio</h1>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <% current_user.portfolio.first.attributes.each do |attribute, value| %>
        <th><%= attribute %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% current_user.portfolio.each do |portfolio_entry| %>
      <tr>
        <% portfolio_entry.attributes.each do |attribute, value| %>
        <td><%= value %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h1>Order History</h1>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <% Order.where(user_id: current_user.id).first.attributes.each do |attribute, value| %>
        <th><%= attribute %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% Order.where(user_id: current_user.id).each do |order| %>
      <tr>
        <% order.attributes.each do |attribute, value| %>
        <td><%= value %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
Name: <%= @user.name %>, Email: <%= @user.email %>